# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import EclassCrawlingModule as Module
import pprint


class Ui_MainWindow(object):
    def __init__(self):
        self.submit_idx = None
        self.info_idx = None
        self.inform_event = None
        f = open("account", encoding='UTF-8')
        account = f.readlines()
        self.secrets = Module.Login(account[0].replace("\n", ''), account[1].replace("\n", ''))

        self.secrets.getSession()
        self.secrets.getUserInfo()
        self.lecture_info = Module.Lecture(self.secrets.s, self.secrets.uid).getLectureList()  # 강의 번호 등 정보
        print(self.lecture_info)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.showSubTable = QtWidgets.QTableWidget(self.groupBox)
        self.showSubTable.setObjectName("showSubTable")
        self.showSubTable.setColumnCount(1)
        self.showSubTable.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubTable.setVerticalHeaderItem(8, item)
        self.showSubTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.showSubTable)
        self.hwPageBtn = QtWidgets.QPushButton(self.groupBox)
        self.subInfoCombo = QtWidgets.QComboBox(self.groupBox)
        self.subInfoCombo.setObjectName("subInfoCombo")
        self.verticalLayout_4.addWidget(self.subInfoCombo)
        self.hwPageBtn.setObjectName("hwPageBtn")
        self.verticalLayout_4.addWidget(self.hwPageBtn)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.showInformTable = QtWidgets.QTableWidget(self.groupBox_3)
        self.showInformTable.setObjectName("showInformTable")
        self.showInformTable.setColumnCount(4)
        self.showInformTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showInformTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showInformTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showInformTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showInformTable.setHorizontalHeaderItem(3, item)
        self.verticalLayout_5.addWidget(self.showInformTable)
        self.informTotalCnt = QtWidgets.QLabel(self.groupBox_3)
        self.informTotalCnt.setObjectName("informTotalCnt")
        self.verticalLayout_5.addWidget(self.informTotalCnt)
        self.anceShowBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.anceShowBtn.setObjectName("anceShowBtn")
        self.verticalLayout_5.addWidget(self.anceShowBtn)
        self.ancePageBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.ancePageBtn.setObjectName("ancePageBtn")
        self.verticalLayout_5.addWidget(self.ancePageBtn)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.showSubmitTable = QtWidgets.QTableWidget(self.groupBox_2)
        self.showSubmitTable.setObjectName("showSubmitTable")
        self.showSubmitTable.setColumnCount(6)
        self.showSubmitTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.showSubmitTable.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.showSubmitTable)
        self.hwSubmitBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.hwSubmitBtn.setObjectName("hwSubmitBtn")
        self.verticalLayout_3.addWidget(self.hwSubmitBtn)

        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_4)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_4.addWidget(self.calendarWidget)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_6.addWidget(self.dateEdit)
        self.dateEdtBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.dateEdtBtn.setObjectName("dateEdtBtn")
        self.verticalLayout_6.addWidget(self.dateEdtBtn)
        self.chkScheduleBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.chkScheduleBtn.setObjectName("chkScheduleBtn")
        self.verticalLayout_6.addWidget(self.chkScheduleBtn)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLogIn = QtWidgets.QAction(MainWindow)
        self.actionLogIn.setObjectName("actionLogIn")
        self.actionShow_Message = QtWidgets.QAction(MainWindow)
        self.actionShow_Message.setObjectName("actionShow_Message")
        self.actionShow_Message_2 = QtWidgets.QAction(MainWindow)
        self.actionShow_Message_2.setObjectName("actionShow_Message_2")
        self.menu.addAction(self.actionLogIn)
        self.menu_2.addAction(self.actionShow_Message)
        self.menu_2.addAction(self.actionShow_Message_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.today_date = self.calendarWidget.selectedDate()
        self.today_date1 = str(self.today_date.getDate()[0]) + ('0'+ str(self.today_date.getDate()[1])) if self.today_date.getDate()[1] < 10 else (self.today_date.getDate()[1])
        self.today_date1 = self.today_date1 + ('0'+ str(self.today_date.getDate()[2])) if self.today_date.getDate()[2] < 10 else self.today_date.getDate()[2]
        self.today_schedule = Module.ConvFunctions(self.secrets.s, self.secrets.uid).getCalender(self.today_date1, 'readSchedule')
        self.showSubmitTable.clicked.connect(self.clickSubmitEvent)
        self.showInformTable.clicked.connect(self.clickInformEvent)
        self.showSubTable.clicked.connect(self.clickInfoEvent)
        self.hwSubmitBtn.clicked.connect(self.clickSubmitButton)
        self.ancePageBtn.clicked.connect(self.clickAnceButton)
        self.hwPageBtn.clicked.connect(self.clickInformEvent)
        #################################################################################################################
        if len(self.today_schedule['title']) == 0:
            self.today_schedule = '일정이 없습니다.'

        self.subInfoCombo.addItems(self.lecture_info.keys())    #combobox에 과목 크롤링 데이터 추가

        basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[0]], 'getClassInfo')
        basic_key = list(basic_data.keys())
        for r in range(int(self.showSubTable.rowCount())):
            self.showSubTable.setItem(r, 0, QtWidgets.QTableWidgetItem(str(basic_data[basic_key[r]][0:])))
        try:
            basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[3]], 'getHomeWorkList')
            basic_key = list(basic_data.keys())
            for row in range (len(basic_data[basic_key[0]])):
                rowPosition = self.showSubmitTable.rowCount()
                self.showSubmitTable.insertRow(rowPosition)
                for col, ky in enumerate(basic_key):
                    self.showSubmitTable.setItem(row, col, QtWidgets.QTableWidgetItem(str(basic_data[ky][row])))

        except Exception:
            pass

        cnt, basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[0]], 'getInformation')
        basic_key = list(basic_data.keys())

        self.informTotalCnt.setText("총 수량 : "+ str(cnt))
        for row in range(len(basic_data[basic_key[1]])):
            rowPosition = self.showInformTable.rowCount()
            self.showInformTable.insertRow(rowPosition)
            for col, ky in enumerate(basic_key):
                self.showInformTable.setItem(row, col, QtWidgets.QTableWidgetItem(str(basic_data[ky][row])))

        self.subInfoCombo.currentIndexChanged.connect(self.getData) #데이터가 바뀌면 실행
    def getData(self):
        selected_row = self.subInfoCombo.currentIndex()
        self.showSubTable.setColumnCount(1)
        self.showSubTable.setRowCount(9)
        self.showSubmitTable.setColumnCount(6)
        self.showSubmitTable.setRowCount(0)
        self.showInformTable.setColumnCount(4)
        self.showInformTable.setRowCount(0)


        basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[selected_row]], 'getClassInfo')
        basic_key = list(basic_data.keys())
        for r in range(int(self.showSubTable.rowCount())):
            self.showSubTable.setItem(r, 0, QtWidgets.QTableWidgetItem(str(basic_data[basic_key[r]][0:])))

        print("HomeWorkList")
        try:
            basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[selected_row]], 'getHomeWorkList')
            basic_key = list(basic_data.keys())
            for row in range (len(basic_data[basic_key[0]])):
                rowPosition = self.showSubmitTable.rowCount()
                self.showSubmitTable.insertRow(rowPosition)
                for col, ky in enumerate(basic_key):
                    self.showSubmitTable.setItem(row, col, QtWidgets.QTableWidgetItem(str(basic_data[ky][row])))

        except Exception:
            pass
        print("Information", self.lecture_info[list(self.lecture_info.keys())[selected_row]])
        cnt, basic_data = Module.Lecture(self.secrets.s, self.secrets.uid).goCategory(self.lecture_info[list(self.lecture_info.keys())[selected_row]], 'getInformation')
        basic_key = list(basic_data.keys())

        self.informTotalCnt.setText("총 수량 : "+ str(cnt))
        print(cnt)
        for row in range(len(basic_data[basic_key[1]])):
            rowPosition = self.showInformTable.rowCount()
            self.showInformTable.insertRow(rowPosition)
            for col, ky in enumerate(basic_key):
                self.showInformTable.setItem(row, col, QtWidgets.QTableWidgetItem(str(basic_data[ky][row])))

        print(selected_row)

    def clickSubmitEvent(self):
        self.submit_idx = self.showSubmitTable.currentRow()

    def clickSubmitButton(self):
        try:
            print(self.submit_idx)
        except exception as e:
            print(e)
            pass

    def clickAnceButton(self):
        try:
            print(self.inform_event)
        except exception as e:
            print(e)
            pass

    def clickInfoButton(self):
        try:
            print(self.info_idx)
        except exception as e:
            print(e)
            pass

    def clickInfoEvent(self):
        self.info_idx = self.showSubTable.currentRow()

    def clickInformEvent(self):
        self.inform_event = self.showInformTable.currentRow()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "과목 보기"))
        item = self.showSubTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "과목"))
        item = self.showSubTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "코드"))
        item = self.showSubTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "교수"))
        item = self.showSubTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "카테고리"))
        item = self.showSubTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "학점/시간"))
        item = self.showSubTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "이메일"))
        item = self.showSubTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "교재"))
        item = self.showSubTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "일정"))
        item = self.showSubTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "반영"))
        self.groupBox_3.setTitle(_translate("MainWindow", "공지 사항"))
        item = self.showInformTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "중요"))
        item = self.showInformTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "제목"))
        item = self.showInformTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "첨부 파일"))
        item = self.showInformTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "등록일"))
        self.informTotalCnt.setText(_translate("MainWindow", "총 수량 :"))
        self.anceShowBtn.setText(_translate("MainWindow", "바로 보기"))
        self.ancePageBtn.setText(_translate("MainWindow", "페이지 이동"))
        self.groupBox_2.setTitle(_translate("MainWindow", "과제 제출"))
        item = self.showSubmitTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "제목"))
        item = self.showSubmitTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "진행도"))
        item = self.showSubmitTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "제출 여부"))
        item = self.showSubmitTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "점수"))
        item = self.showSubmitTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "배점"))
        item = self.showSubmitTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "마감일"))
        self.hwSubmitBtn.setText(_translate("MainWindow", "과제 제출"))
        self.hwPageBtn.setText(_translate("MainWindow", "강의 목록"))
        self.groupBox_4.setTitle(_translate("MainWindow", "스케줄 관리"))
        self.dateEdtBtn.setText(_translate("MainWindow", "추가/삭제"))
        self.chkScheduleBtn.setText(_translate("MainWindow", "일정 확인"))
        self.menu.setTitle(_translate("MainWindow", "설정"))
        self.menu_2.setTitle(_translate("MainWindow", "기타 기능"))
        self.actionLogIn.setText(_translate("MainWindow", "Change Account"))
        self.actionShow_Message.setText(_translate("MainWindow", "메시지 보기"))
        self.actionShow_Message_2.setText(_translate("MainWindow", "선택한 과목 강의자료 다운로드"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
